source ~/.dotfiles/dots/bash/rc
source ~/.dotfiles/dots/bash/prompt

export EDITOR="nvim"
export SUDO_EDITOR="nvim"

# opencode
export PATH=/home/stube/.opencode/bin:$PATH

# pnpm
export PNPM_HOME="/home/stube/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME/bin:"*) ;;
  *) export PATH="$PNPM_HOME/bin:$PATH" ;;
esac
# pnpm end
